### PR TITLE
fix for PHP 7.2

### PR DESCRIPTION
**Pull request by devbrom**

### CODE REVIEW

**Review by greeflas — CHANGES_REQUESTED** [review]
This issue will be fixed in 4.0 version. See #15. But thank you for your contributing!

**Comment by devbrom** [comment]
In 4.0 there is no stable release. Maybe added this changes in minor release 3.0.2

**Comment by greeflas** [comment]
@devbrom I can't add this change to bug fix release because we are using semantic versioning and this fix break down back compability.

**Comment by greeflas** [comment]
@devbrom Hi! I have just released version 4.0.0 with fix of this issue. You can use it :)

**Pull request closed without merging**
